// Precompile Phase 5 JSON Schemas into ESM validator modules (AJV standalone)
// Deterministic, no network, stable ordering.
import fs from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import Ajv from 'ajv'
import standaloneCode from 'ajv/dist/standalone/index.js'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)

async function ensureDir(p) {
  await fs.mkdir(p, { recursive: true })
}

function baseNameFromSchemaFile(file) {
  // e.g., ui_catalog.schema.json -> ui_catalog
  return path.basename(file).replace(/\.schema\.json$/i, '')
}

async function readJSON(file) {
  const txt = await fs.readFile(file, 'utf8')
  return JSON.parse(txt)
}

async function writeText(file, text) {
  await ensureDir(path.dirname(file))
  await fs.writeFile(file, text, 'utf8')
}

async function main() {
  // Project layout assumptions: this script lives at repoRoot/tools/
  // We compile schemas that live in onyx-hall-phase5-app/tools/schemas/
  const appDir = path.resolve(__dirname, '../onyx-hall-phase5-app')
  const schemaDir = path.join(appDir, 'tools', 'schemas')
  const outDir = path.join(appDir, 'src', 'renderer', 'src', 'validators')

  // Read all *.schema.json files in stable order
  let entries
  try {
    entries = await fs.readdir(schemaDir)
  } catch (e) {
    console.error(`Schema directory not found: ${schemaDir}`)
    process.exitCode = 1
    return
  }
  const schemaFiles = entries
    .filter((f) => /\.schema\.json$/i.test(f))
    .sort((a, b) => a.localeCompare(b))

  const ajv = new Ajv({ allErrors: true, strict: false, code: { source: true } })

  // Load and register all schemas first (in case of cross-$ref)
  const loaded = []
  for (const file of schemaFiles) {
    const full = path.join(schemaDir, file)
    const schema = await readJSON(full)
    const key = schema.$id || baseNameFromSchemaFile(file)
    ajv.addSchema(schema, key)
    loaded.push({ file, full, key, schema })
  }

  // Compile each to a standalone ESM module
  const indexLines = [
    '// AUTO-GENERATED FILE. Do not edit by hand.',
    '// Generated by tools/precompile_phase5_schemas.mjs',
  ]
  const importLines = []
  const exportNames = []

  for (const { file, key, schema } of loaded) {
    const name = baseNameFromSchemaFile(file)
    // Compile; pass the original schema object to preserve IDs
    const validate = ajv.compile(schema)
    const moduleCode = standaloneCode(ajv, validate, { esm: true })
    const outFile = path.join(outDir, `${name}.validator.js`)
    await writeText(
      outFile,
      `// AUTO-GENERATED by precompile_phase5_schemas.mjs\n` + moduleCode
    )
    const importName = `validate_${name.replace(/[^a-zA-Z0-9_$]/g, '_')}`
    importLines.push(`import ${importName} from './${name}.validator.js'`)
    exportNames.push(`  '${name}': ${importName}`)
  }

  // Write index that exports a name->validator map and named exports
  const indexPath = path.join(outDir, 'index.js')
  const namedExports = loaded
    .map(({ file }) => {
      const name = baseNameFromSchemaFile(file)
      const importName = `validate_${name.replace(/[^a-zA-Z0-9_$]/g, '_')}`
      return `export { ${importName} as ${name} }`
    })
    .join('\n')

  const indexSource = [
    ...indexLines,
    ...importLines,
    namedExports,
    '',
    'const validators = {',
    ...exportNames,
    '}',
    '',
    'export default validators',
    '',
  ].join('\n')

  await writeText(indexPath, indexSource)

  console.log(
    `Precompiled ${loaded.length} schema(s) to ${path.relative(appDir, outDir)}`
  )
}

main().catch((err) => {
  console.error(err)
  process.exitCode = 1
})
